// <auto-generated />
namespace ETicaretOtomasyonv2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tax_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tax_add));
        
        string IMigrationMetadata.Id
        {
            get { return "202402081955321_tax_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
